### ISSUE TITLE
Cambiar Ruta Raíz / Change Root Path

### ISSUE THREAD

**Issue by Zeisdark** [bangnokia/laravel-serve-livereload#4]
@bangnokia 

Hola soy nuevo en laravel y estoy intentando mover el public a la carpeta raíz del servidor por lo que me gustaría saber como puedo cambiar la carpeta public del live serve.

#####
Hello I am new to laravel and I am trying to move the public to the root folder of the server so I would like to know how I can change the public folder of the live serve.

**Comment by bangnokia** [comment]
@haloants7  
if you don't use built-in php web server but something like wamp, xamp,..., you can only run the websockets server via this command `php artisan serve:websockets`

**Comment by Zeisdark** [comment]
No me entendiste xd. lo que quiero es cambiar la carpeta public para que el websockets busque el index en esta nueva carpeta.


You didn't understand me xd. what I want is to change the public folder so that the websockets look for the index in this new folder.

**Comment by bangnokia** [comment]
@haloants7 
you can run command `php artisan vendor:publish --provider="BangNokia\ServeLiveReload\CommandServiceProvider"` to publish the configuration file to configure your own need to be watched folders. the file in `config/serve_livereload.php`

**Comment by Zeisdark** [comment]
Muchas gracias amigo XD a funcionado correctamente.  puedo ejecutar el servidor desde la carpeta raíz de mi proyecto, el websockets para el live reload y ejecutarlo desde mi servidor local sin hacer cambios.

Thank you very much friend XD it worked correctly. I can run the server from the root folder of my project, the websockets for the live reload and run it from my local server without making changes.
