### ISSUE TITLE
how to launch it correctly

### ISSUE THREAD

**Issue by steeves66** [bangnokia/laravel-serve-livereload#5]
the url of my app is: http://127.0.0.1:8000

After this:
Starting Laravel development server: http://127.0.0.1:8000
[Sat Dec 12 19:56:46 2020] PHP 7.4.10 Development Server (http://127.0.0.1:8000) started      
Websockets server started: ws://127.0.0.1:1322

 I don't know how to launch my app

I don't understand the gif video
You can help me please.

**Comment by bangnokia** [comment]
@steeves66 you simply open browser and go to http://127.0.0.1:8000, you don't have to care about websockets server.
